name: Change Commit Author on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  change-author:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install GitHub CLI from Snap
        run: |
            sudo apt update
            sudo apt install -y snapd
            sudo snap install gh
            git config --global user.name "Suresh Thelkar"
            git config --global user.email "sthelkar@microsoft.com"
      - name: Get PR Reviewer
        if: github.event.pull_request.merged == true
        run: |
          echo "Reading event payload..."
          cat $GITHUB_EVENT_PATH
          REVIEWER=$(jq -r '.pull_request.requested_reviewers.login' < $GITHUB_EVENT_PATH)
          echo "Reviewer: $REVIEWER"
      - name: Print pull request event data
        run: |
            echo "Pull Request Event Data:"
            cat $GITHUB_EVENT_PATH | jq '.pull_request'
