name: Change Commit Author on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  change-author:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get PR Reviewer
        if: github.event.pull_request.merged == true
        run: |
          echo "Reading event payload..."
          cat $GITHUB_EVENT_PATH
          if jq -e '.pull_request.requested_reviewers | length > 0' < $GITHUB_EVENT_PATH > /dev/null; then
            REVIEWER=$(jq -r '.pull_request.requested_reviewers[0].login' < $GITHUB_EVENT_PATH)
            echo "Reviewer: $REVIEWER"
          else
            echo "No reviewers found in the pull request."
          fi
      - name: Display commit IDs of this PR
        run: |
          echo "Commit IDs in this PR:"
          jq -r '.pull_request.commits_url' < $GITHUB_EVENT_PATH | xargs curl -s | jq -r '.[].sha'
      - name: Print pull request event data
        run: |
            echo "Pull Request Event Data:"
            cat $GITHUB_EVENT_PATH | jq '.pull_request'
